### ISSUE TITLE
(Bug) (Windows) `wally install` fails with `error loading known-hosts: ; class-Ssh (23)`

### ISSUE THREAD

**Issue by zachshattuck** [UpliftGames/wally#190]
Overview
---
Hey all, I'm fairly new to Roblox development and am setting up a basic Aftman/Rojo/Wally project.
When trying to run `wally install` after adding a package to the .toml file, I am given the following error message:
```
> wally install
Error cloning Git repository https://github.com/UpliftGames/wally-index

Caused by:
    error loading known_hosts: ; class=Ssh (23)
```

My `known_hosts` file exists in the standard location (`~/.ssh/known_hosts`) and I am able to clone [UpliftGames/wally-index](https://github.com/UpliftGames/wally-index) via SSH normally.

After some digging, it seems like it's likely related to [this known issue in `git2-rs` versions 0.16 and below,](https://github.com/rust-lang/git2-rs/issues/937) - classic Windows pathname weirdness. I see that the current version of wally uses `git2@0.16.2`. It's possible that just updating to v0.17.0 will fix this.

Any help would be appreciated!

More information
---
aftman 0.3.0
Rojo 7.4.4
wally 0.3.2
Windows 11 Home v10.0.22631 Build 22631  

wally.toml:
```toml
[package]
name = "zdogs/roblox-game-1"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
React = "jsdotlua/react@17.0.0"
```
