### ISSUE TITLE
Cannot import Quenty/NevermoreEngine packages

### ISSUE THREAD

**Issue by cassis163** [UpliftGames/wally#39]
The naming convention that is used for NevermoreEngine's packages is not allowed.
```toml
[dependencies]
TimeSyncService = "@quenty/timesyncservice@^3.0.0"
```
Returns: "a package requirement is of the form SCOPE/NAME@VERSION_REQ for key `dependencies.TimeSyncService`"
