### ISSUE TITLE
`wally install` loads some dependencies of shared realm in the ServerPackages folder

### ISSUE THREAD

**Issue by flamenco687** [UpliftGames/wally#66]
When a server dependency depends on a shared package that is not already in `Packages._Index`, wally installs that shared package only in the `ServerPackages` folder, but the link to that shared package found inside the server dependency folder looks for the shared package in the `Packages` folder path instead.

- Main package:

  ```toml
  [package]
  name = "flamenco687/game"
  
  version = "0.0.1"
  
  registry = "https://github.com/UpliftGames/wally-index/"
  realm = "shared"
  
  [dependencies]
  Knit = "sleitnick/knit@^1"
  Signal = "sleitnick/signal@^1"
  Fusion = "elttob/fusion@0.1.1-beta"
  Promise = "evaera/promise@3"
  Maid = "flamenco687/maid@^1"
  Proxy = "flamenco687/roblox-proxy@^1"
  
  [server-dependencies]
  Bank = "flamenco687/bank@^1.0.0-beta"
  
  [place]
  shared-packages = "game.ReplicatedStorage.Packages"
  server-packages = "game.ServerScriptService.Packages"
  ```
- Server dependency (Bank)
  ```toml
  [package]
  name = "flamenco687/bank"
  description = "Lightweight data management module/wrapper for Roblox using DataStoreService"
  
  version = "1.0.0-beta"
  license = "MIT License"
  authors = ["flamenco687"]
  
  registry = "https://github.com/UpliftGames/wally-index"
  realm = "server"
  
  exclude = [
      "test.project.json",
      "foreman.toml",
      "README.md",
      "LICENSE",
      "Exclude",
  ]
  
  [dependencies]
  TableUtil = "sleitnick/table-util@^1"
  Signal = "sleitnick/signal@^1"
  Promise = "evaera/promise@^3"
  Proxy = "flamenco687/roblox-proxy@^1"
  Error = "flamenco687/error@^1"
  Maid = "flamenco687/maid@^1"
  ```
- Shared dependency not being included in the `Packages` folder:
  ```toml
  [package]
  name = "flamenco687/error"
  description = "Roblox library to quickly throw out clean & detailed errors"
  
  version = "1.1.0"
  license = "MIT License"
  
  authors = ["flamenco687"]
  realm = "shared"
  
  registry = "https://github.com/UpliftGames/wally-index"
  
  exclude = [
      "docs", 
      "foreman.toml",
      "test.project.json",
      "README.md",
      "LICENSE"
  ]
  ```
- Link to the shared dependency that is being generated when installing Bank:
  ```lua
  return require(game.ReplicatedStorage.Packages._Index["flamenco687_error@1.1.0"]["error"])
  ```
<p align="center">

<img width="200" src="https://user-images.githubusercontent.com/36084202/143056549-6b728491-251d-41fc-9c20-49eea8c68704.png" alt="Material Bread logo">

<p>
