### ISSUE TITLE
Improve authentication methods to wally

### ISSUE THREAD

**Issue by ThatTimothy** [UpliftGames/wally#94]
# Current authentication

Before I explain what I want to change, let me show what the current authentication looks like.

## For reference:

- `Read` = Ability to search and download packages
- `Write` = Ability to publish packages

| Method            | Description                                             | Example Rocket.toml auth                                                                                                |
| ----------------- | ------------------------------------------------------- | ----------------------------------------------------------------------------------------------------------------------- |
| `api-key`         | A single api key which grants `read` and `write` access | <pre lang="toml">auth = { type = "api-key", value = "a-secret" }</pre>                                                  |
| `double-api-key`  | Two api keys, one for `read`ing and one for `writ`ing   | <pre lang="toml">auth = { type = "double-api-key", value = { read = "a-read-secret", write = "a-write-secret" } }</pre> |
| `github-o-auth`   | Anyone can `read`, can `write` to authenticated scope   | <pre lang="toml">auth = { type = "github-o-auth" }</pre>                                                                |
| `unauthenticated` | Anyone can `read`, nobody can write                     | <pre lang="toml">auth = { type = "unauthenticated" }</pre>                                                              |

*Note that this is not documented anywhere, so you have to [go digging in code to figure this out](https://github.com/UpliftGames/wally/blob/6c984ea171cb9fbd22a1c1e5c183c925acb1ddce/wally-registry-backend/src/auth.rs#L17-L24).*

The public wally registry uses `github-o-auth` currently.

# Issues

The current setup for authentication does not support a few features that would greatly increase usability, specifically in private repos.

## Multiple API keys

Currently, only one API key is supported for an entire registry. While `double-api-key` provides two keys, it would still be one key for the entire registry. This is a real limitation if you want to support multiple users, as every user would have to share the same key.

Ideally, the format could look like this:
```toml
# TOML standard array format:

[[auth]]
type = "api-key"
value = "secret1"

[[auth]]
type = "api-key"
value = "secret2"

# TOML inline array:

auth = [ { type = "api-key", value = "secret1" }, { type = "api-key", value = "secret2" } ]

```

## Granular permissions

Wally current as no support for granular permissions. What this would mean is the ability to restrict access for a certain credential (API key or oauth) to read, write, or both.

Ideally, this would allow restricting via a permissions field.

Example for an api key:

```toml
[[auth]]
type = "api-key"
value = "secret"
permissions = { read = true, write = false}
```

Additionally, this should work with github auth, at the user level:

```toml
[[auth]]
type = "github-o-auth"
value = "user:ThatTimothy"
permissions = { read = true, write = false}
```

Org level:

```toml
[[auth]]
type = "github-o-auth"
value = "org:UpliftGames"
permissions = { read = true, write = false}
```

Team level:

```toml
[[auth]]
type = "github-o-auth"
value = "team:UpliftGames/team"
permissions = { read = true, write = true}
```

Authenticated level:

```toml
[[auth]]
type = "github-o-auth"
value = "authenticated"
permissions = { read = true, write = true}
```

Also, there should of course be default permissions (when no other auth patterns apply)

```toml
[[auth]]
type = "default"
permissions = { read = false, write = false }
```

This change would make users have no permission by default, until given it by another auth rule.

## Interlocking authentication methods

Currently, only api keys OR github oauth can be used to authenticate.

Ideally, both could be supported, with some way of the client requesting available auth methods (writing to `config.json`?) to prompt the user with. This would allow github oauth for users and api keys for CI/CD.

# Conclusion

I realize this is a lot of information and doesn't have all of the specific implementation details included. This would also likely be a **breaking change**, at least for current backend configs.

I wanted to get feedback on these ideas before I go and do all the work for nothing. Once we nail down the details, I'd be willing to make a PR and get to work.

Thanks for reading!
